#47 Improve compile error when missing maven.compiler.release property
Original error:
java.util.NoSuchElementException: No value present ... thrown by ServiceProcessor.findModule (ServiceProcessor.java:397)

New error:
java.lang.IllegalStateException:
Maven pom is missing maven.compiler.release. Look to add <maven.compiler.release>21</maven.compiler.release> into the properties section. Refer to https://github.com/avaje/avaje-spi-service/wiki/Compile-Error